version: '3.2'

volumes:
  tmp-data:

services:
  app:
    image: golang:1.14-stretch # Image page: <https://hub.docker.com/_/golang>
    working_dir: /src
    network_mode: host
    environment:
      HOME: /tmp
      GOPATH: /tmp
      WEBCRAWLER_HTTPPORT: 8001
      WEBCRAWLER_WORKERS: 20
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/src:cached
      - ./build:/build:cached
      - ./go.mod:/src/go.mod
      - ./go.sum:/src/go.sum
      - tmp-data:/tmp:cached
